// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqlcnomndlmhnytumpor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxbGNub21uZGxtaG55dHVtcG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTU5NjksImV4cCI6MjA2NTUzMTk2OX0.JlgMbBfCGp0zcgiF0ye6zT6kD3OJ3o9W01KDZSBTRRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);